### ISSUE TITLE
check/uncheck in time-travel-todo performs poorly in Chrome on large lists

### ISSUE THREAD

**Issue by vlazar** [rijs/fullstack#25]
First of all - I'm astonished by rendering speed demos. Thank you for your great work! I'm so happy I found this tiny modular framework!

Noticed one issue with time travel todo app example though. When I add about 50 items to the list, toggling checkboxes became really slow. This is in Chrome only.

I assume this issue is somehow related to time travel debugger only and has nothing to do with general cases. Just a little bit worried, if there something to keep in mind when using rijs (similarly to number of watchers in Angular, for example).

**Comment by pemrouz** [comment]
@vlazar, thanks for raising this issue +1.

There is no concept of watchers in Ripple. The [view layer](https://github.com/rijs/components) is a lot more simple than that. 

In general, with the "game loop" philosophy to rendering, you change state/data, and rerender everything (as much as is necessary). This greatly simplifies the complexity of components ([as explained here](https://github.com/rijs/docs/blob/master/components.md#guide-to-writing-components)) but since rerenders become cheap, sometimes we may overrender. In this case, it took 50 unnecessary rerenders before we started dropping a frame or two, so in perspective the DOM-level memoizations carried out by [once](https://github.com/utilise/once#once) alone is doing pretty well.

In order to highlight all renders and render times, you can use the [rijs/perf](https://github.com/rijs/perf#ripple--perf) module (the [todo app.js is so simple `ripple(require('./'))`](https://github.com/rijs/examples/blob/master/time-travel-todo/package.json#L11) I kept it in a npm script, but normally you would put this in a proper `.js` file):  

```diff
+ "bundle": "sh -c 'echo \"require(\\'rijs.perf\\').default(ripple); ripple(require(\\'./dist/index.js\\'))\" | browserify - -o dist/app.js",
- "bundle": "sh -c 'echo \"ripple(require(\\'./dist/index.js\\'))\" | browserify - -o dist/app.js",
```

This immediately highlights that every `todo-item` is being redrawn when a single item changes. This makes sense looking at the code, since the [`todo-app` depends on `items`](https://github.com/rijs/examples/blob/master/time-travel-todo/index.html#L18), which then [redraws all visible `todo-items`](https://github.com/rijs/examples/blob/master/time-travel-todo/src/resources/todo-app/todo-app.js#L16).

To solve precisely this problem, in the [last release](https://github.com/rijs/fullstack/releases/tag/v0.5.4) the active change was exposed:

> #### Active Change

> Ripple now exposes the active changes that occured to trigger the render to components. There is only one change (`{ key, value, type, time }`) that may be flowing through the system, but since components are rAF batched, there be multiple changes that occur between frames so they are queued on the element (`.change`). Having access directly to the fine-grained, low-level changes allows components to better check whether a render can be skipped. 

Using this, in https://github.com/rijs/examples/commit/fd5125a52d1031abe6a578d5cec5ac6c047cc1d1, I've used the [change details](https://github.com/rijs/examples/blob/master/time-travel-todo/src/resources/todo-app/todo-app.js#L29-L38) (i.e. if there was one change (1) and that change was to `items` (2) and only one item changed (3), pass down details of the key) to [skip over rendering of irrelevant `todo-item`s](https://github.com/rijs/examples/blob/master/time-travel-todo/src/resources/todo-item/todo-item.js#L2) (normally you would check here against something like an ID, rather than index). 

Now we are back to being maximally efficient as shown by logs (i.e. updating only _exactly_ what needs to be re-rendered). 50+ items and it's fast. There's still a bit of lag at 100+ because the `timetravel-debugger` is now huge and could also be further optimised. If you go ahead and delete that element via the inspector, you'll see that even with 200+ items the `todo-app` is instantly fast.

Parsing the raw array of change details is currently not the most ergonomic. If and when (hopefully after playing with this across several more use cases) I am able to genericise some pure helper functions, I'll make them available in [utilise](https://github.com/utilise/utilise#lean-javascript-utilities-as-micro-libraries) and blog about it in the releases here.

Note: This is all conceptually similar to `shouldComponentMount` in React. You could also follow their thinking and use something like ImmutableJS. However, (1) [I'm personally leaning towards achieving similar benefits with log-based structures](https://github.com/rijs/fullstack#immutablejs-mori) and (2) it's sufficient to simply `return` early at the top of a component to bail out of a render - a framework-specific hook is not necessary.

**Comment by vlazar** [comment]
Wow! Thanks again for all your work and for pointing me into high direction with such a detailed explanation.

You are absolutely right about this:
> There's still a bit of lag at 100+ because the timetravel-debugger is now huge and could also be further optimised. If you go ahead and delete that element via the inspector, you'll see that even with 200+ items the todo-app is instantly fast.

I've also tried to hide `timetravel-debugger` element with `display: none` and checkboxes can be checked/unchecked instantly with 100+ items.

So I went into `Developer Tools -> Timeline` and recorded toggle checkbox action with `timetravel-debugger` element shown. It looks like the problem is with how Chrome re-renders the page after changes. The enormous amount of the time is spent in `Layout` after I toggle checkbox (300+ milliseconds). When I hide `timetravel-debugger` element with `display: none` there is no such huge time spent in `Layout` and checkboxes work perfectly.

I've also re-checked this in Safari, and there is no such issue. Checkboxes can be checked/unchecked instantly even without your recent changes.

So I pretty sure this is style-related issue, as DOM operations are insanely fast in `rijs` already.

One thing I've noticed is that `timetravel-debugger` element positioned absolutely and overlaps `<todo-app>` element (see this when you shower over elements in Element inspector). Safari works fine with this layout, but Chrome does to much work re-layouting stuff.

**Comment by pemrouz** [comment]
Thanks for the extra performance insight @vlazar :+1:. When trying to see [how far we could push](http://mathieuancelin.github.io/js-repaint-perfs/once/) vanilla rendering speed (with decent developer ergonomics), I also found it quite strange Chrome too often required to relayout _everything_ and [asked the same question to the Google devs](https://twitter.com/pemrouz/status/717798846487740416) (/cc @paullewis @paulirish @addyosmani). Whilst the future CSS containment property seems like a nice way to express this behaviour, it appeared to me that Chrome could do a better job of optimising existing elements that have some combination of `position:absolute`, `overflow: hidden`, `display: block`, etc set (i.e. no knock-on effects). I never tried this in Safari, but it's good to hear that they don't re-layout everything and that this is a browser-specific performance issue that could potentially be improved in the future.

**Comment by paulirish** [comment]
what's the easiest way i can reproduce the what @vlazar described? (assuming i know zero about the project)

**Comment by pemrouz** [comment]
Open: https://rawgithub.com/rijs/examples/master/time-travel-todo/index.html

Add loads of todos, then profile in Chrome and Safari.

**Comment by paulirish** [comment]
fun one. 

`attr(details)` tooltips that are `opacity:0` are your cost.

you still pay the layout cost of opacity:0 stuff. set those to display:none and it comes back to life.

we can't really magically make those layouts faster as its a LOT of text. so you'll have to avoid keeping them in your layout until you actually need them.

**Comment by pemrouz** [comment]
Thanks @paulirish! :) 

Although I'm not sure that's exactly the issue @vlazar found that differed between Chrome/Safari (I'll leave it to him to clarify if so). 

In any case, I investigated again what is required in order to limit the scope of layout updates (in Chrome), and it seems that a combination of `position: absolute`, `overflow: hidden` and fixed `width/height` does in fact limit layouts. [Simple gist here](http://bl.ocks.org/pemrouz/9353cbd14bd3b73520db915e7213dd8f): 

![image](https://cloud.githubusercontent.com/assets/2184177/15627594/bb20f24e-24e0-11e6-8e89-8da9c6b8d07f.png)

I'm not sure why this didn't work on [DBMonster](file:///C:/Users/King/Documents/cloud/js-repaint-perfs/ripple/index.html) earlier when I tried..

**Comment by paulirish** [comment]
Yup that's called a layout root and it's a pro technique! Nice one.
